### PR TITLE
updated `reqwest` to 0.9

### PR DESCRIPTION
**Pull request by simeonschaub**

### CODE REVIEW

**Comment by simeonschaub** [comment]
45fe140 should now fix #2

**Comment by jens1o** [comment]
@Nervengift Could you consider merging this pr? The `sofort -> 0` fix would be important for me.

**Comment by Nervengift** [comment]
Sorry, the mail got lost. Thanks for the pr @simeonschaub !

**Comment by jens1o** [comment]
Thank you! :)

**Pull request merged**
